main:
  path: /home/jdwang/PycharmProjects/weiboDataProcesss/preprocess/main.py
  name: data_preprocess_main
  describe: 对数据进行预处理主函数——调用其他函数
  log_file_path: log/preprocess_main_20160524.log

data_filter:
  path: /home/jdwang/PycharmProjects/weiboDataProcesss/preprocess/data_filter.py
  name: data_filter
  describe: 对数据进行预处理——去除非法字符，只留下中文
  data_file_path: /media/jdwang/My Book/复旦大学/SMP-Weibo/sample/weibodata.csv
  output_file_path: /media/jdwang/My Book/复旦大学/SMP-Weibo/sample/weibodata_filter.csv
  log_file_path: log/data_filter_20160524.log

data_segment:
  path: /home/jdwang/PycharmProjects/weiboDataProcesss/preprocess/data_segment.py
  name: data_segment
  describe: 对数据进行预处理——切词
  input_file_path: /media/jdwang/My Book/复旦大学/SMP-Weibo/sample/weibodata_filter.csv
  output_file_path: /media/jdwang/My Book/复旦大学/SMP-Weibo/sample/weibodata_segment.csv
  log_file_path: log/data_segment_20160524.log

